[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "release-triage"
version = "0.1.0"
[dependencies]
petgraph = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.semver]
features = ["serde"]
version = "*"
